language: java
jdk:
  - openjdk8
  - openjdk11

env:
- TOMCAT_VERSION=8.5.29
- TOMCAT_VERSION=9.0.12

install:
- ./gradlew clean
- wget http://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_VERSION:0:1}/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.zip
- unzip apache-tomcat-$TOMCAT_VERSION.zip
- chmod a+x apache-tomcat-$TOMCAT_VERSION/bin/*.sh
- apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start

script:
- ./gradlew build
- cp build/libs/joinfaces-gradle-war-example.war apache-tomcat-$TOMCAT_VERSION/webapps/
- timeout --preserve-status 60s tail -f apache-tomcat-$TOMCAT_VERSION/logs/catalina.out || true
- wget localhost:8080/joinfaces-gradle-war-example/index.xhtml
- grep "Hello from Spring" index.xhtml
